name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 코드 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} <<EOF
            cd /home/ubuntu/portfolio
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx
            EOF
            
      - name: Debug Secrets
        run: echo "EC2_HOST is ${{ secrets.EC2_HOST}}"
